#!/bin/bash

echo "=== Test des nouvelles fonctionnalités Pi Collide ==="
echo ""
echo "🔊 SONS:"
echo "  - Son joué à chaque collision (bloc-bloc et bloc-mur)"
echo "  - Optimisation: arrêt du son précédent avant le nouveau"
echo ""
echo "⬆️ CONTRÔLES AJOUTÉS:"
echo "  - FLÈCHE HAUT   : Multiplier la masse par 10"
echo "  - FLÈCHE BAS    : Diviser la masse par 10"
echo "  - Limites       : Min 1kg, Max 100M kg"
echo ""
echo "📊 AFFICHAGE AMÉLIORÉ:"
echo "  - Rapport de masse affiché en temps réel"
echo "  - Instructions mises à jour"
echo "  - Console affiche les changements de masse"
echo ""
echo "🎮 TOUS LES CONTRÔLES:"
echo "┌─────────────────┬──────────────────────────────────┐"
echo "│ Touche          │ Action                           │"
echo "├─────────────────┼──────────────────────────────────┤"
echo "│ 1, 2, 3, 4      │ Sélectionner expérience prédéf.  │"
echo "│ ESPACE          │ Démarrer/Recommencer simulation  │"
echo "│ R               │ Reset rapide                     │"
echo "│ FLÈCHE HAUT ⬆   │ Masse × 10                      │"
echo "│ FLÈCHE BAS ⬇    │ Masse ÷ 10                      │"
echo "│ ESC             │ Quitter                          │"
echo "└─────────────────┴──────────────────────────────────┘"
echo ""
echo "💡 EXEMPLES D'UTILISATION:"
echo "1. Commencer par l'expérience 2 (touche '2')"
echo "2. Appuyer ESPACE pour démarrer"
echo "3. Observer ~31 collisions pour approximer π"
echo "4. Utiliser FLÈCHE HAUT pour masse × 10"
echo "5. Recommencer avec ESPACE"
echo ""
echo "🎯 MASSES INTÉRESSANTES:"
echo "- 100     → π × 10 ≈ 31 collisions"
echo "- 1,000   → π × 31 ≈ 99 collisions"  
echo "- 10,000  → π × 100 ≈ 314 collisions"
echo "- 100,000 → π × 316 ≈ 999 collisions"
echo ""

if [ -f "pi_collide" ]; then
    echo "✅ Programme compilé et prêt!"
    echo ""
    echo "Pour lancer:"
    echo "  ./pi_collide"
else
    echo "❌ Programme non compilé. Utilisez 'make' d'abord."
fi
